lang = {
    AddPatient : "Add Patient",
    greeting : "Hi",
    Dashboard : "dashboard",
    Reviews : "Reviews" , 
    ExamplePage : "Example Page",
    Bookings : " Bookings" ,
    UserArea : "User Area" , 
    MyProfile : "My Profile" , 
    SingOut : "Sing Out" ,
    BasicInformations : "Basic Informations",
    FirstName :"First Name",
    LastName : "Last Name" , 
    AppointmentType :"Appointment Type",
    Examination :"Examination",
    Consultation : "Consultation",
    Operation :"Operation",
    Cancel : "Cancel",
    Logout : "Logout",
    ExamplePages: "ExamplePages" , 
    Bookings : "Bookings" , 
    SingOut : "Sing Out" , 
    Previous: "Previous" ,
    ReadytoLeave : "Ready to Leave ?",
    Home : "Home",
    MyFavorites :"My Favorites" , 
    Delete: "Delete" , 
    Next :"Next" , 
    Edit : "Edit" , 
    OpenNow : "Open Now ! ",
    Save :"Save " , 
    Hospital :"Hospital" , 
    UploadImage : "Upload Image ",
    Phone : "Phone" , 
    Education :" Education" , 
    address : " address ",
    cost : " cost " , 
    Age : "Age " ,
    gender : "gender" , 
    rating : "rating" ,
    Experienceyears : "Experience years ",
    Awards :"Awards",
    HospitalAffiliations : "Hospital Affiliations" ,
    ProfessionalMemberships : "Professional Memberships" , 
    Appointment : "Appointment ",
    LatestBookings : "Latest Bookings" , 
    LatestReviews : "Latest Reviews" , 
    RegisterNow : "Register Now" , 
    LoginPage : "Login Page",
    Email : "Email",
    Password : "Password " , 
    doaccount : "Don't you have an account? ",
    Singin : "Sing in",
    SingUpPage : "Sing Up Page" , 
    YourGender : "Your Gender",
    Male : "Male" , 
    Female : " Female " , 
    YourCity : "YourCity " , 
    TermsandConditions : "Terms and Conditions" , 
    Iacceptthe : "I accept the" , 
    Completesignup : "Complete sign up ! " 
};