const settings = require('electron-settings');
var getlang =settings.get('User.lang');
// if(getlang==null){
// settings.set('User', {'lang': 'ar'})
//     }

var lang=getlangg(getlang);
// $(document).ready(function() {

function getlangg(getlang){
if(getlang=='ar'){
return lang = {

    AddPatient : "إضافة مريض",
    Dashboard : "لوحة التحكم",
    AvailableTime:"الوقت المتاح",
    Date:"التاريخ",
    AddedPatients:"المرضى المضافين",
    Reviews : "التقيمات" , 
    ExamplePage : "Example Page",
    Bookings : " الحجوزات " ,
    UserArea : "مساحة المستخدم" , 
    MyProfile : "الملف الشخصي " , 
    SingOut : "تسجيل الخروج" ,
    BasicInformations : "معلومات شخصيه ",
    FirstName :"الأسم الأول ",
    LastName : "الأسم الأخير " , 
    phone : "رقم الهاتف" , 
    AppointmentType :"نوع الحجز",
    AppointmentTime :"ميعاد الحجز",
    Today :"اليوم",
    Calender:"النتيجة",
    Examination :"فحص (كشف)",
Consultation : "استشارة (إعادة كشف )  ",

speciality:"التخصص",
   Operation :"عملية ",
    Cancel : "إلغاء ",
    Logout : "تسجيل الخروج",
    ExamplePages: "الصفحات" , 
    Bookings : "الحجوزات " , 
    SingOut : "تسجيل الخروج" , 
    Previous: "السابق " ,
    ReadytoLeave : "هل تريد المغادرة؟ ",
    Home : "الرئيسيه",
    MyFavorites :"المفضله " , 
    Delete: "حذف" , 
    Next :"التالي" , 
    Edit : "تعديل " , 
    OpenNow : "فتح ! ",
    Save :"حفظ " , 
    Hospital :"مستشفى" , 
    UploadImage : "رفع صوره  ",
    Phone : "رقم الهاتف " , 
    Education :" التعليم " , 
    address : " العنوان  ",
    cost : " السعر  " , 
    Age : "السن  " ,
    gender : "الجنس" , 
    rating : "التقييم " ,
    Experienceyears : "سنوات الخبره  ",
    Awards :"الجوائز",
    HospitalAffiliations : "وسائل الراحه " ,
    ProfessionalMemberships : "عضويه مهنيه " , 
    Appointment : "حجز ",
    Appointments : "الحجوزات",
    LatestBookings : "الحجوزات الأخيره " , 
    LatestReviews : "التقييمات الأخيره " , 
    RegisterNow : "سجل الآن " , 
    LoginPage : "تسجيل الدخول",
    Email : "البريد الإلكتروني ",
    Password : "كلمة السر" , 
    doaccount : "هل تمتلك حساب ؟  ",
    Singin : "تسجيل الدخول",
    SingUpPage : "سجل الأن " , 
    YourGender : "الجنس",
    Male : "ذكر" , 
    Female : " أنثى " , 
    YourCity : "المحافظه " , 
    TermsandConditions : "الشروط و الأحكام " ,
    oftheapp : "للتطبيق" ,  
    Iacceptthe : "موافق " , 
    Completesignup : "أكمل عملية التسجيل  " ,
    TotalReviews: "التقيمات",
    currentsession: "اختر تسجيل الخروج من الاسفل"
}
}

if(getlang=='en'){
   return lang = {
    AddPatient : "Add Patient",
    greeting : "Hi",
    Dashboard : "Dashboard",
    AvailableTime:"Available Time",
    AddedPatients:"Added Patients",
    Date:"Date",
    Reviews : "Reviews" , 
    YourPassword:"Your Password",
    YourEmail:"YourEmail",
    ExamplePage : "Example Page",
    Bookings : " Bookings" ,
    speciality:"speciality",
    UserArea : "User Area" , 
    MyProfile : "My Profile" , 
    SingOut : "Sing Out" ,
    BasicInformations : "Basic Informations",
    FirstName :"First Name",
    LastName : "Last Name" , 
    phone : "Phone Number" , 
    AppointmentType :"Appointment Type",
    AppointmentTime :"Appointment Time",
    Today:"Today",
    Calender:"Calender",
    Examination :"Examination",
    Consultation : "Consultation",
    Operation :"Operation",
    Cancel : "Cancel",
    Logout : "Logout",
    ExamplePages: "Pages" , 
    Bookings : "Bookings" , 
    SingOut : "Sing Out" , 
    Previous: "Previous" ,
    ReadytoLeave : "Ready to Leave ?",
    Home : "Home",
    MyFavorites :"My Favorites" , 
    Delete: "Delete" , 
    Next :"Next" , 
    Edit : "Edit" , 
    OpenNow : "Open Now ! ",
    Save :"Save " , 
    Hospital :"Hospital" , 
    UploadImage : "Upload Image ",
    Phone : "Phone" , 
    Education :" Education" , 
    address : " address ",
    cost : " cost " , 
    Age : "Age " ,
    gender : "gender" , 
    rating : "rating" ,
    Experienceyears : "Experience years ",
    Awards :"Awards",
    HospitalAffiliations : "Hospital Affiliations" ,
    ProfessionalMemberships : "Professional Memberships" , 
    Appointment : "Appointment ",
    Appointments : "Appointments ",
    LatestBookings : "Latest Bookings" , 
    LatestReviews : "Latest Reviews" , 
    RegisterNow : "Register Now" , 
    LoginPage : "Login Page",
    Email : "Email",
    Password : "Password " , 
    doaccount : "Don't you have an account? ",
    Singin : "Sing in",
    SingUpPage : "Sing Up Page" , 
    YourGender : "Your Gender",
    Male : "Male" , 
    Female : " Female " , 
    YourCity : "YourCity " , 
    TermsandConditions : "Terms and Conditions" , 
    oftheapp : "of the App" , 
    Iacceptthe : "I accept the" , 
    Completesignup : "Complete sign up ! " ,
    TotalReviews: "Total Reviews" ,
    currentsession: "Select 'Logout' below if you are ready to end your current session."
};

}}